### ISSUE TITLE
Help! Lire "music thing" isn't working

### ISSUE THREAD

**Issue by heybob88** [GabrielTK/DropMeter#2]
I downloaded DropMeter, WebNowPlaying, and Lire. The user interface shows Lire as a loaded widget. When downloaded, WebNowPlaying showed need to "restart Dropmeter". I restarted my computer, shutdown and reopened the application, and redownloaded the softwares, nothing worked. I was never able to get WebNowPlaying to show up and when I tried playing  music nothing showed up. Please Help!

**Comment by heybob88** [comment]
Here is a picture of my desktop, in case this helps. 
![image](https://user-images.githubusercontent.com/78919095/107775850-da0a2600-6d0e-11eb-9ace-2b6736872d07.png)

**Comment by GabrielTK** [comment]
Hello there! I’ll be happy to help you! Would you like to join our Discord Server, so I can have a better look at your environment?

**Comment by heybob88** [comment]
Is there a link for the server?

**Comment by GabrielTK** [comment]
Yup, at the README.md file. Will get it in a sec.

**Comment by GabrielTK** [comment]
https://discord.gg/DBE44yU

**Comment by GabrielTK** [comment]
I'll, unfortunately, have to leave for a while, so I'll just leave what I made of your screenshot here:
It seems everything has been setup correctly. If you don't see anything, it is probably because you setup your music player incorrectly for WebNowPlaying. I recommend you check that. If you are using spotify, [this guide](https://github.com/khanhas/spicetify-cli/wiki/Guide-for-Rainmeter-user) will help you.

**Comment by GabrielTK** [comment]
Having received no answer, I will assume this has been solved and, therefore, close this issue.
